- id: nickel-eval
  name: Evaluate Nickel
  description: This hook ensures that Nickel code can be evaluated.
  language: rust
  entry: nickel-rain eval
  files: \.(ncl)$
- id: nickel-format
  name: Format Nickel
  description: This hook ensures that Nickel code is formatted.
  language: rust
  entry: nickel-rain format
  files: \.(ncl)$
