[package]
name = "nickel-pre-commit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nickel-rain"
path = "src/main.rs"

[dependencies]
nickel-lang-core = { git = "https://github.com/tweag/nickel.git", rev = "7fe5946", features = ["format"] }
clap = "4.4.11"
tempfile = "3.8.1"